services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
  express-app:
    container_name: express-app
    image: waltherbeach/docker-pipeline-exercise
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8080:8080
